modLoader="javafml"
loaderVersion="[32,)"
logoFile="logo.png"
[[mods]]
    modId="discernment"
    version="${version}"
    displayName="Discernment"
    description='''
This mod adds a discernment enchantment that prevents a living entity (including a player) from damaging any peaceful mob while the following conditions are met:
1) The entity is wearing an item as armor, or holding an item in their main or off hand, that has this enchantment on it.
2) The entity is not sneaking.
'''
    issueTrackerURL="https://github.com/Phylogeny/Discernment/issues"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/discernment"
    updateJSONURL="https://github.com/Phylogeny/Discernment/raw/1.16.1/update.json"
    credits=""
    authors="Phylogeny"
[[dependencies.discernment]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.discernment]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"